import EXAMPLE_MOBILES from 'libphonenumber-js/examples.mobile.json';
import { type CountryCode, getExampleNumber, parsePhoneNumberFromString } from 'libphonenumber-js/min';
import { CALL_RATES_USD } from '../data/call-rates';
import { GEO_PERMITTED_COUNTRIES } from '../data/callable-countries';

/*
 * What a call to a given number costs us, and whether we are willing to place
 * it at all.
 *
 * Twilio bills programmable voice in whole minutes, rounded up, and our script
 * (two <Say> blocks around an 8s <Gather>) never reaches one. Verified against
 * real calls: 12s, 19s, 22s and 32s to the same Indian mobile each billed
 * exactly $0.0496. So the per-minute rate IS the per-call cost, flat.
 *
 * That matters because we always ring mobiles, and mobile termination is
 * nothing like landline termination. A German landline is under 3 cents; a
 * German mobile is 37. Gating on a country's cheapest rate would wave through
 * exactly the calls that lose the most money.
 *
 * Price is only one of two gates. The Twilio account holds geographic dialing
 * permissions for a few dozen countries, and every destination outside them is
 * refused by the carrier at call time with error 21215 regardless of what it
 * costs. A number must clear both gates, here, before anything downstream is
 * allowed to promise a call.
 */

/**
 * Dearest destination we will ring. Above this, onboarding stops and we log the
 * interest instead.
 *
 * Set at gross break-even: both paid shapes work out to $0.10 a call ($5 for 50,
 * and the $2 top-up pack of 20), so the priciest destination we accept earns
 * what it costs and no more. Net it is slightly worse than that, since Dodo's
 * cut comes off the $5 first, so true break-even sits a shade under $0.10 and a
 * call at the cap is a small loss.
 *
 * That is deliberate rather than overlooked. Almost nothing is priced at the
 * cap, and the gap between it and a typical call is where the margin and the
 * free tier are both paid for: the US is $0.014, the UK $0.031, India $0.050.
 *
 * Held inclusively, so a destination priced at exactly the cap is in. Thailand
 * is $0.10 on the nose, which is what pins that in the tests.
 */
export const MAX_CALL_RATE_USD = 0.1;

/**
 * Longest key in the table, so lookup starts where it can actually hit.
 *
 * Must be at least as long as the longest key, or that key becomes unreachable
 * and its number falls through to a shorter, cheaper prefix, admitting exactly
 * the calls this gate exists to refuse. Asserted against the data in
 * call-rates.test.ts, since the table is regenerated by a tool that lives
 * outside this repo.
 */
export const MAX_PREFIX_DIGITS = 12;

/**
 * The table entry that prices a number: which prefix matched, and at what.
 *
 * Longest-prefix wins, because price is per prefix and not per country. Under
 * +44 alone, the country code itself is $0.0158 while +4470 is $0.5577 and +449
 * is $1.0479, so matching on the country code would let every premium range in
 * the world hide behind a cheap one.
 */
export function priceCall(e164: string): { prefix: string; usd: number } | undefined {
  const digits = e164.replace(/\D/g, '');
  for (let end = Math.min(digits.length, MAX_PREFIX_DIGITS); end > 0; end--) {
    const prefix = digits.slice(0, end);
    const usd = CALL_RATES_USD[prefix];
    if (usd !== undefined) return { prefix, usd };
  }
  return undefined;
}

/** USD per call to this number, or undefined when no prefix matches */
export function callRateUsd(e164: string): number | undefined {
  return priceCall(e164)?.usd;
}

/**
 * Whether we will ring this number today: priced within the cap, and in a
 * country the account's geographic permissions allow Twilio to dial.
 *
 * Both gates are real refusals we have watched happen. Without the price
 * gate we lose money per call; without the permission gate the visitor is
 * offered the demo or walked through onboarding, and then the carrier
 * declines the call itself with error 21215 and they see nothing but a
 * blank failure.
 *
 * Fails closed twice, for the same reason each time. An unpriced prefix is
 * the one case where guessing is unbounded, so absent means no. And a number
 * libphonenumber cannot pin to a country is a destination we cannot check
 * against the permissions at all, so it gets the same answer: the phrasing
 * differs but the philosophy is one piece, a destination we cannot vouch for
 * is a destination we do not ring.
 */
export function isCallableNumber(e164: string): boolean {
  const rate = callRateUsd(e164);
  if (rate === undefined || rate > MAX_CALL_RATE_USD) return false;
  const country = parsePhoneNumberFromString(e164)?.country;
  return country !== undefined && GEO_PERMITTED_COUNTRIES.has(country);
}

/**
 * Whether a country is one we could ring at all: in the account's geographic
 * permissions, and with a typical mobile number there priced within the cap.
 *
 * A country is not really the unit we gate on, so this is an approximation and
 * only ever used to decide what to *show* someone: a real number is still
 * checked on its own prefix. It has to be the mobile example rather than the
 * country's calling code, because the code alone is the wrong granularity in
 * both directions. +49 prices a German landline at 3 cents while German mobile
 * is 38, and +44 has ranges from 1.5 cents to a dollar.
 *
 * The permission set is consulted before any pricing because it is the cheap
 * check and the unconditional one: nothing about a country's rates matters if
 * the carrier will not connect it.
 *
 * Unknown country still means yes, but only in the sense it always did: a code
 * libphonenumber has no example mobile for is one we know nothing about, this
 * decides whether to offer something, and being coy with someone we could
 * serve is the worse mistake. A country we do know that is missing from the
 * permission set is not unknown, it is refused. Nothing about spending money
 * rests on any of it.
 */
export function isSupportedCountry(iso: string): boolean {
  const country = iso.toUpperCase() as CountryCode;
  if (!GEO_PERMITTED_COUNTRIES.has(country)) {
    return getExampleNumber(country, EXAMPLE_MOBILES) === undefined;
  }
  const example = getExampleNumber(country, EXAMPLE_MOBILES);
  if (!example) return true;
  return isCallableNumber(example.number);
}
