import EXAMPLE_MOBILES from 'libphonenumber-js/examples.mobile.json';
import { type CountryCode, getExampleNumber } from 'libphonenumber-js/min';
import { CALL_RATES_USD } from '../data/call-rates';

/*
 * What a call to a given number costs us, and whether we are willing to place
 * it at all.
 *
 * Twilio bills programmable voice in whole minutes, rounded up, and our script
 * (two <Say> blocks around an 8s <Gather>) never reaches one. Verified against
 * real calls: 12s, 19s, 22s and 32s to the same Indian mobile each billed
 * exactly $0.0496. So the per-minute rate IS the per-call cost, flat.
 *
 * That matters because we always ring mobiles, and mobile termination is
 * nothing like landline termination. A German landline is under 3 cents; a
 * German mobile is 37. Gating on a country's cheapest rate would wave through
 * exactly the calls that lose the most money.
 */

/**
 * Dearest destination we will ring. Above this, onboarding stops and we log the
 * interest instead.
 *
 * Set at gross break-even: both paid shapes work out to $0.10 a call ($5 for 50,
 * and the $2 top-up pack of 20), so the priciest destination we accept earns
 * what it costs and no more. Net it is slightly worse than that, since Dodo's
 * cut comes off the $5 first, so true break-even sits a shade under $0.10 and a
 * call at the cap is a small loss.
 *
 * That is deliberate rather than overlooked. Almost nothing is priced at the
 * cap, and the gap between it and a typical call is where the margin and the
 * free tier are both paid for: the US is $0.014, the UK $0.031, India $0.050.
 *
 * Held inclusively, so a destination priced at exactly the cap is in. Thailand
 * is $0.10 on the nose, which is what pins that in the tests.
 */
export const MAX_CALL_RATE_USD = 0.1;

/**
 * Longest key in the table, so lookup starts where it can actually hit.
 *
 * Must be at least as long as the longest key, or that key becomes unreachable
 * and its number falls through to a shorter, cheaper prefix, admitting exactly
 * the calls this gate exists to refuse. Asserted against the data in
 * call-rates.test.ts, since the table is regenerated by a tool that lives
 * outside this repo.
 */
export const MAX_PREFIX_DIGITS = 12;

/**
 * The table entry that prices a number: which prefix matched, and at what.
 *
 * Longest-prefix wins, because price is per prefix and not per country. Under
 * +44 alone, the country code itself is $0.0158 while +4470 is $0.5577 and +449
 * is $1.0479, so matching on the country code would let every premium range in
 * the world hide behind a cheap one.
 */
export function priceCall(e164: string): { prefix: string; usd: number } | undefined {
  const digits = e164.replace(/\D/g, '');
  for (let end = Math.min(digits.length, MAX_PREFIX_DIGITS); end > 0; end--) {
    const prefix = digits.slice(0, end);
    const usd = CALL_RATES_USD[prefix];
    if (usd !== undefined) return { prefix, usd };
  }
  return undefined;
}

/** USD per call to this number, or undefined when no prefix matches */
export function callRateUsd(e164: string): number | undefined {
  return priceCall(e164)?.usd;
}

/**
 * Whether we will ring this number today.
 *
 * Fails closed on an unknown prefix. Twilio lists a few countries it cannot
 * route from this account at all (sanctions, no carrier), and an unpriced
 * destination is the one case where guessing is unbounded, so absent means no.
 */
export function isCallableNumber(e164: string): boolean {
  const rate = callRateUsd(e164);
  return rate !== undefined && rate <= MAX_CALL_RATE_USD;
}

/**
 * Whether a country is one we could ring at all, judged by pricing a typical
 * mobile number there.
 *
 * A country is not really the unit we gate on, so this is an approximation and
 * only ever used to decide what to *show* someone: a real number is still
 * checked on its own prefix. It has to be the mobile example rather than the
 * country's calling code, because the code alone is the wrong granularity in
 * both directions. +49 prices a German landline at 3 cents while German mobile
 * is 38, and +44 has ranges from 1.5 cents to a dollar.
 *
 * Unknown or unset country means yes: this decides whether to offer something,
 * and being coy with someone we could serve is the worse mistake. Nothing about
 * spending money rests on it.
 */
export function isSupportedCountry(iso: string): boolean {
  const example = getExampleNumber(iso.toUpperCase() as CountryCode, EXAMPLE_MOBILES);
  if (!example) return true;
  return isCallableNumber(example.number);
}
